# Generated by Django 4.0 on 2021-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='premium',
            new_name='premium_quantity',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='regular',
            new_name='regular_quantity',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='vip',
            new_name='vip_quantity',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(to='api.Ticket'),
        ),
    ]
