# Generated by Django 4.0 on 2021-12-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticket_rename_premium_event_premium_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='premium_quantity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='regular_quantity',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='vip_quantity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='serial_number',
            field=models.PositiveSmallIntegerField(default=11, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tickettype')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.price'),
        ),
    ]
