# Generated by Django 4.0 on 2021-12-21 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_order_number_alter_ticket_serial_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ticket',
            field=models.ManyToManyField(to='api.Ticket'),
        ),
    ]
