# Generated by Django 4.0 on 2021-12-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ticket_order_order_price_order_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
