# Generated by Django 4.0 on 2022-01-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0006_remove_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ManyToManyField(related_name='orders', to='api.Ticket'),
        ),
        migrations.AlterField(
            model_name='price',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='api.event'),
        ),
        migrations.AlterField(
            model_name='price',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prices', to='api.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='api.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='api.price'),
        ),
    ]
